# custom app config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

version: "3.2"

services:

  app:
    depends_on:
      - cloud
    labels:
      - traefik.http.middlewares.${APP_TAG}-redirect.redirectregex.regex=/.well-known/(card|cal)dav
      - traefik.http.middlewares.${APP_TAG}-redirect.redirectregex.replacement=/remote.php/dav/
      - traefik.http.middlewares.${APP_TAG}-redirect1.redirectregex.regex=/.well-known/webfinger
      - traefik.http.middlewares.${APP_TAG}-redirect1.redirectregex.replacement=/index.php/.well-known/webfinger
      - traefik.http.middlewares.${APP_TAG}-redirect2.redirectregex.regex=/.well-known/nodeinfo
      - traefik.http.middlewares.${APP_TAG}-redirect2.redirectregex.replacement=/index.php/.well-known/nodeinfo
       # hsts middleware defined in DCAPE/apps/traefik/docker-compose.inc.yml
      - traefik.http.routers.${APP_TAG}.middlewares=hsts,${APP_TAG}-redirect,${APP_TAG}-redirect1,${APP_TAG}-redirect2
    volumes:
      - ${APP_ROOT}/data:/var/www/html:ro
      - ${APP_ROOT}/nginx.conf:/etc/nginx/nginx.conf:ro

  cloud:
    image: ${CLOUD_IMAGE}:${CLOUD_IMAGE_VER}
    restart: always
    depends_on:
      - cache
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${APP_ROOT}/data:/var/www/html
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=${USER_NAME}
      - NEXTCLOUD_ADMIN_PASSWORD=${USER_PASS}
      - NEXTCLOUD_TRUSTED_DOMAINS=${APP_SITE}
      - REDIS_HOST=cloud-cache
      - REDIS_HOST_PASSWORD=${REDIS_PASS}

  cache:
    image: ${REDIS_IMAGE}:${REDIS_IMAGE_VER}
    restart: always
    command: redis-server --requirepass ${REDIS_PASS}
    sysctls:
      net.core.somaxconn: 511
    volumes:
      - ${APP_ROOT}/redis:/var/lib/redis

  cron:
    image: rcdailey/nextcloud-cronjob
    restart: always
    network_mode: none
    depends_on:
      - cloud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_CONTAINER_NAME=cloud
      - NEXTCLOUD_PROJECT_NAME=dcape-app-nextcloud
      - NEXTCLOUD_EXEC_SHELL=sh
